# Generated by Django 5.1.6 on 2025-04-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_category_category_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category'),
        ),
    ]
