# Generated by Django 5.1.6 on 2025-04-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Address',
            new_name='address',
        ),
    ]
